# Generated by Django 4.0.4 on 2022-05-24 10:07

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Cars',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('brand', models.CharField(blank=True, default='', max_length=200)),
                ('model_name', models.CharField(blank=True, default='', max_length=200)),
            ],
        ),
    ]
